### ISSUE TITLE
confusion about challenges from third parties 

### ISSUE THREAD

**Issue by nikitaborisov** [ietf-wg-privacypass/draft-ietf-privacypass-rate-limit-tokens#15]
> Issuers need to ensure that they
> only allow rate-limiting on expected origins, which for the case of websites
> with challenges originating from third-parties would generally be the
> first-party name.

I found this a little confusing. Is this talking about a third-party resource sending a rate-limited challenge? If so, what is the rationale behind this generally being the first-party name? I can imagine a third party wanting to have some protection / rate limits across different first-party instances, e.g., a widget that you can embed that allows you to create a Disqus account. 

Also, how is the issuer going to ensure this? The issuer has no context about who the first or third party are since they are not party to the web transaction.

**Comment by tfpauly** [comment]
The challenge doesn't need to include both origin names — but if it does include both, and the third party sends a challenge that includes the first party, it is essentially indicating that this is a rate limit that applies to the first party. This lines up with the normal challenge / auth scheme behavior. But yeah, I can make this more clear.
