### ISSUE TITLE
policy window issues

### ISSUE THREAD

**Issue by nikitaborisov** [ietf-wg-privacypass/draft-ietf-privacypass-rate-limit-tokens#16]
I have a few questions / concerns about policy windows in the current draft:

1. Since policy windows are fixed per-issuer, that means that a single issuer cannot enforce policies of 3x/day and 10x/month at the same time. This seems to limit the flexibility of origins working with a given issuer. I'm not strongly opposed to this because in the current design you want to limit the policy diversity anyway. I guess my questions are a) is my understanding correct and b) should there be text about how an issuer chooses a policy window and therefore its impact on rate limitation policies?
2. How does an attester learn about the issuer policy window? Is the attester assumed to know the issuer configuration / discover it somehow? Apologies if I missed this.
3. The document doesn't have explicit recommendations for how long windows can be (I think a month is used in the example). Given this, client rekey penalization based on policy windows doesn't make sense to me. If the length is a month, it seems that a well-behaved client can certainly lose their keys twice within a two-month period (“a well-behaved Client will never change keys this frequently”); if the length is an hour, allowing the clients to rekey every two hours seems excessive
4. I think the text should be more explicit about the fact that client key rotation resets the client access tracking for the remaining policy window. Perhaps something like "If a client loses the client secret, the attester MAY allow the client to generate a new client key and secret and register the client key. However this will reset the client's policy window and thus could be used to exceed the rate limits, so an attester MUST penalize clients that register new keys too frequently"

**Comment by tfpauly** [comment]
1. If you have multiple policy windows, you just create multiple issuer names. Like "issuer-vendora-month", "issuer-vendora-day", etc. Nothing stops having more issuer names here.
2. The configuration is defined here: https://www.ietf.org/archive/id/draft-ietf-privacypass-rate-limit-tokens-01.html#name-configuration
3. That's a good point, we should update that text
4. Yes, also a very good point!
