### ISSUE TITLE
Rate limiting context

### ISSUE THREAD

**Issue by chris-wood** [ietf-wg-privacypass/draft-ietf-privacypass-rate-limit-tokens#18]
In a web context, it's sensible for the rate limiting context to be an origin in the TokenChallenge's list of origins. But if this protocol is to be used outside of the web context, does that same restriction need to apply? It seems reasonable to, for example, allow applications to apply meaning to the context in which rate limits are applied. One example would be if we were to use this Privacy Pass tokens in DAP as a Sybil mitigation.

**Comment by tfpauly** [comment]
Should we in that case have the "origin_info" field contain more info than just the hostname? Can you provide a concrete example?

**Comment by chris-wood** [comment]
As an example, imagine a single origin wanted to apply different rate limits to different resources, `/foo` and `/bar`. As far as I can tell, there's no real technical reason why we wouldn't allow different rate limits to be applied in this way. Forcing applications to use different origins for implementing rate limits for these two resources seems like it'd make adoption more difficult. It would be nice if we had reasonable options for these types of use cases.

**Comment by tfpauly** [comment]
Ah, I see. That makes sense.
